package com.company;

import org.json.JSONException;
import org.json.JSONObject;

import javax.swing.*;
import java.io.IOException;

public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1 = new javax.swing.JLabel();
        LoginInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        ErrorLoginText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ReturnCodeButton = new javax.swing.JButton();
        RecoveryPassword = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Увійти в аккаунт");
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        LoginInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginInput.setToolTipText("");

        PasswordInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Логін");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Пароль");

        RegisterButton.setText("Реестрація");
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setContentAreaFilled(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        ErrorLoginText.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setText("Увійти");
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ReturnCodeButton.setText("Ввести код");
        ReturnCodeButton.setForeground(new java.awt.Color(255, 255, 255));
        ReturnCodeButton.setContentAreaFilled(false);
        ReturnCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCodeButtonActionPerformed(evt);
            }
        });

        RecoveryPassword.setText("Забули пароль");
        RecoveryPassword.setForeground(new java.awt.Color(255, 255, 255));
        RecoveryPassword.setContentAreaFilled(false);
        RecoveryPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoveryPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ReturnCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RecoveryPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LoginInput)
                                                .addComponent(PasswordInput)
                                                .addComponent(ErrorLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(LoginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ErrorLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegisterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RecoveryPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReturnCodeButton)
                                .addGap(38, 38, 38))
        );
    }// </editor-fold>

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Main.lock.closeLoginPanel();
        Main.lock.displayRegisterPanel();
    }

    private void ReturnCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Main.lock.closeLoginPanel();
        Main.lock.displayCodePanel();
    }

    private void RecoveryPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Main.lock.closeLoginPanel();
        Main.lock.displayRecoveryPanel();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String login = LoginInput.getText().trim();
        String password = new String(PasswordInput.getPassword());

        String jsonString = new JSONObject()
                .put("login", login)
                .put("password", password)
                .toString();

        try {
            String response = Main.httpPostRequest(Main.LoginEndpoint, jsonString);

            try {
                System.out.println(response);
                JSONObject out = new JSONObject(response);

                if (out.has("errors")) {
                    JSONObject errors = out.getJSONObject("errors");

                    if (errors.has("error")) {
                        ErrorLoginText.setText(errors.get("error").toString());
                    }
                } else {
                    int timeLeft = (int) out.get("time");

                    if (timeLeft == 0) {
                        ErrorLoginText.setText("Час гры вичерпано");
                    }

                    Main.processLoginAuthResponse(out);
                }
            } catch (JSONException e) {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel ErrorLoginText;
    public javax.swing.JTextField LoginInput;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton RecoveryPassword;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton ReturnCodeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration
}