package com.company;

import org.json.JSONException;
import org.json.JSONObject;

import javax.swing.*;
import java.io.IOException;

public class RecoveryPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecoveryPanel
     */
    public RecoveryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1 = new javax.swing.JLabel();
        RecoveryEmailInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SendNewPasswordButton = new javax.swing.JButton();
        RecoveryErrorMessage = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Відновити пароль");

        RecoveryEmailInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Почта");

        SendNewPasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SendNewPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        SendNewPasswordButton.setContentAreaFilled(false);
        SendNewPasswordButton.setText("Відправити новий пароль");
        SendNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendNewPasswordButtonActionPerformed(evt);
            }
        });

        RecoveryErrorMessage.setForeground(new java.awt.Color(255, 0, 51));

        ReturnButton.setText("Назад");
        ReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        ReturnButton.setContentAreaFilled(false);
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(RecoveryErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(RecoveryEmailInput)
                                                                        .addComponent(SendNewPasswordButton)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(75, 75, 75)
                                                                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(RecoveryEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(11, 11, 11)
                                .addComponent(SendNewPasswordButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RecoveryErrorMessage)
                                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void SendNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String email = RecoveryEmailInput.getText().trim();

        String jsonString = new JSONObject()
                .put("email", email)
                .toString();

        try {
            String response = Main.httpPostRequest(Main.RecoveryEndpoint, jsonString);

            try {
                System.out.println(response);
                JSONObject out = new JSONObject(response);

                if (out.has("errors")) {
                    JSONObject errors = out.getJSONObject("errors");

                    if (errors.has("email")) {
                        RecoveryErrorMessage.setText(errors.get("email").toString());
                    }
                } else {
                    RecoveryErrorMessage.setText("Новый пароль відправлено на почту");
                }
            } catch (JSONException e) {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), e.getMessage());
        }
    }

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Main.lock.closeRecoveryPanel();
        Main.lock.displayLoginPanel("");
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField RecoveryEmailInput;
    private javax.swing.JLabel RecoveryErrorMessage;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SendNewPasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration
}
